export interface DistrictLocation {
    name: string;
    subAreas: string[];
}

export interface DivisionLocation {
    name: string;
    districts: DistrictLocation[];
}

export const bangladeshLocations: DivisionLocation[] = [
    {
        name: 'Dhaka',
        districts: [
            {
                name: 'Dhaka',
                subAreas: [
                    'Dhanmondi',
                    'Gulshan',
                    'Banani',
                    'Uttara',
                    'Mirpur',
                    'Mohammadpur',
                    'Motijheel',
                    'Tejgaon',
                    'Paltan',
                    'Ramna',
                    'Badda',
                    'Khilgaon',
                    'Jatrabari',
                    'Wari',
                    'Lalbagh',
                    'Sutrapur',
                    'Shahbagh',
                ],
            },
            {
                name: 'Gazipur',
                subAreas: [
                    'Gazipur Sadar',
                    'Tongi',
                    'Kaliakair',
                    'Kapasia',
                    'Sreepur',
                    'Kaliganj',
                ],
            },
            {
                name: 'Narayanganj',
                subAreas: [
                    'Narayanganj Sadar',
                    'Fatullah',
                    'Siddhirganj',
                    'Bandar',
                    'Rupganj',
                    'Araihazar',
                    'Sonargaon',
                ],
            },
            {
                name: 'Narsingdi',
                subAreas: [
                    'Narsingdi Sadar',
                    'Belabo',
                    'Monohardi',
                    'Palash',
                    'Raipura',
                    'Shibpur',
                ],
            },
            {
                name: 'Manikganj',
                subAreas: [
                    'Manikganj Sadar',
                    'Saturia',
                    'Shivalaya',
                    'Singair',
                    'Harirampur',
                    'Ghior',
                    'Daulatpur',
                ],
            },
            {
                name: 'Munshiganj',
                subAreas: ['Munshiganj Sadar', 'Sreenagar', 'Lohajang', 'Sirajdikhan', 'Tongibari', 'Gazaria'],
            },
            {
                name: 'Tangail',
                subAreas: [
                    'Tangail Sadar',
                    'Basail',
                    'Bhuapur',
                    'Delduar',
                    'Dhanbari',
                    'Ghatail',
                    'Gopalpur',
                    'Kalihati',
                    'Madhupur',
                    'Mirzapur',
                    'Nagarpur',
                    'Sakhipur',
                ],
            },
            {
                name: 'Kishoreganj',
                subAreas: [
                    'Kishoreganj Sadar',
                    'Bajitpur',
                    'Bhairab',
                    'Hossainpur',
                    'Itna',
                    'Karimganj',
                    'Katiadi',
                    'Kuliarchar',
                    'Mithamain',
                    'Nikli',
                    'Pakundia',
                    'Tarail',
                ],
            },
            {
                name: 'Madaripur',
                subAreas: [
                    'Madaripur Sadar',
                    'Kalkini',
                    'Rajoir',
                    'Shibchar',
                ],
            },
            {
                name: 'Gopalganj',
                subAreas: [
                    'Gopalganj Sadar',
                    'Kashiani',
                    'Kotalipara',
                    'Muksudpur',
                    'Tungipara',
                ],
            },
            {
                name: 'Faridpur',
                subAreas: [
                    'Faridpur Sadar',
                    'Alfadanga',
                    'Bhanga',
                    'Boalmari',
                    'Charbhadrasan',
                    'Madhukhali',
                    'Nagarkanda',
                    'Sadarpur',
                    'Saltha',
                ],
            },
            {
                name: 'Rajbari',
                subAreas: [
                    'Rajbari Sadar',
                    'Baliakandi',
                    'Goalanda',
                    'Kalukhali',
                    'Pangsha',
                ],
            },
            {
                name: 'Shariatpur',
                subAreas: [
                    'Shariatpur Sadar',
                    'Bhedarganj',
                    'Damudya',
                    'Gosairhat',
                    'Naria',
                    'Zajira',
                ],
            },
        ],
    },

    {
        name: 'Chattogram',
        districts: [
            {
                name: 'Chattogram',
                subAreas: [
                    'Kotwali',
                    'Panchlaish',
                    'Pahartali',
                    'Halishahar',
                    'Bakalia',
                    'Chandgaon',
                    'Bayezid',
                    'Patenga',
                    'Double Mooring',
                    'Anwara',
                    'Boalkhali',
                    'Hathazari',
                    'Mirsharai',
                    'Patiya',
                    'Rangunia',
                    'Raozan',
                    'Sandwip',
                    'Satkania',
                    'Sitakunda',
                    'Lohagara',
                    'Fatikchhari',
                ],
            },
            {
                name: "Cox's Bazar",
                subAreas: [
                    "Cox's Bazar Sadar",
                    'Chakaria',
                    'Eidgaon',
                    'Kutubdia',
                    'Maheshkhali',
                    'Pekua',
                    'Ramu',
                    'Teknaf',
                    'Ukhia',
                ],
            },
            {
                name: 'Cumilla',
                subAreas: [
                    'Cumilla Sadar',
                    'Barura',
                    'Brahmanpara',
                    'Burichang',
                    'Chandina',
                    'Chauddagram',
                    'Daudkandi',
                    'Debidwar',
                    'Homna',
                    'Laksam',
                    'Meghna',
                    'Monoharganj',
                    'Muradnagar',
                    'Nangalkot',
                    'Titas',
                ],
            },
            {
                name: 'Brahmanbaria',
                subAreas: [
                    'Brahmanbaria Sadar',
                    'Ashuganj',
                    'Akhaura',
                    'Bancharampur',
                    'Bijoynagar',
                    'Kasba',
                    'Nabinagar',
                    'Nasirnagar',
                    'Sarail',
                ],
            },
            {
                name: 'Chandpur',
                subAreas: [
                    'Chandpur Sadar',
                    'Faridganj',
                    'Haimchar',
                    'Haziganj',
                    'Kachua',
                    'Matlab North',
                    'Matlab South',
                    'Shahrasti',
                ],
            },
            {
                name: 'Feni',
                subAreas: [
                    'Feni Sadar',
                    'Chagalnaiya',
                    'Daganbhuiyan',
                    'Fulgazi',
                    'Parshuram',
                    'Sonagazi',
                ],
            },
            {
                name: 'Lakshmipur',
                subAreas: [
                    'Lakshmipur Sadar',
                    'Kamalnagar',
                    'Raipur',
                    'Ramganj',
                    'Ramgati',
                ],
            },
            {
                name: 'Noakhali',
                subAreas: [
                    'Noakhali Sadar',
                    'Begumganj',
                    'Chatkhil',
                    'Companiganj',
                    'Hatiya',
                    'Kabirhat',
                    'Senbagh',
                    'Sonaimuri',
                    'Subarnachar',
                ],
            },
            {
                name: 'Khagrachhari',
                subAreas: [
                    'Khagrachhari Sadar',
                    'Dighinala',
                    'Lakshmichhari',
                    'Mahalchhari',
                    'Manikchhari',
                    'Matiranga',
                    'Panchhari',
                    'Ramgarh',
                ],
            },
            {
                name: 'Rangamati',
                subAreas: [
                    'Rangamati Sadar',
                    'Baghaichhari',
                    'Barkal',
                    'Belaichhari',
                    'Juraichhari',
                    'Kaptai',
                    'Langadu',
                    'Naniarchar',
                    'Rajasthali',
                ],
            },
            {
                name: 'Bandarban',
                subAreas: [
                    'Bandarban Sadar',
                    'Alikadam',
                    'Lama',
                    'Naikhongchhari',
                    'Rowangchhari',
                    'Ruma',
                    'Thanchi',
                ],
            },
        ],
    },

    {
        name: 'Rajshahi',
        districts: [
            {
                name: 'Rajshahi',
                subAreas: [
                    'Boalia',
                    'Rajpara',
                    'Motihar',
                    'Shah Makhdum',
                    'Paba',
                    'Godagari',
                    'Tanore',
                    'Bagha',
                    'Bagmara',
                    'Charghat',
                    'Durgapur',
                    'Mohanpur',
                    'Puthia',
                ],
            },
            {
                name: 'Bogura',
                subAreas: [
                    'Bogura Sadar',
                    'Adamdighi',
                    'Dhunat',
                    'Dhupchanchia',
                    'Gabtali',
                    'Kahaloo',
                    'Nandigram',
                    'Sariakandi',
                    'Shajahanpur',
                    'Sherpur',
                    'Shibganj',
                    'Sonatala',
                ],
            },
            {
                name: 'Pabna',
                subAreas: [
                    'Pabna Sadar',
                    'Atgharia',
                    'Bera',
                    'Bhangura',
                    'Chatmohar',
                    'Faridpur',
                    'Ishwardi',
                    'Santhia',
                    'Sujanagar',
                ],
            },
            {
                name: 'Natore',
                subAreas: [
                    'Natore Sadar',
                    'Bagatipara',
                    'Baraigram',
                    'Gurudaspur',
                    'Lalpur',
                    'Singra',
                ],
            },
            {
                name: 'Naogaon',
                subAreas: [
                    'Naogaon Sadar',
                    'Atrai',
                    'Badalgachhi',
                    'Dhamoirhat',
                    'Manda',
                    'Mahadebpur',
                    'Niamatpur',
                    'Patnitala',
                    'Porsha',
                    'Raninagar',
                    'Sapahar',
                ],
            },
            {
                name: 'Chapainawabganj',
                subAreas: [
                    'Chapainawabganj Sadar',
                    'Bholahat',
                    'Gomastapur',
                    'Nachole',
                    'Shibganj',
                ],
            },
            {
                name: 'Joypurhat',
                subAreas: [
                    'Joypurhat Sadar',
                    'Akkelpur',
                    'Kalai',
                    'Khetlal',
                    'Panchbibi',
                ],
            },
            {
                name: 'Sirajganj',
                subAreas: [
                    'Sirajganj Sadar',
                    'Belkuchi',
                    'Chauhali',
                    'Kamarkhanda',
                    'Kazipur',
                    'Raiganj',
                    'Shahjadpur',
                    'Tarash',
                    'Ullahpara',
                ],
            },
        ],
    },

    {
        name: 'Khulna',
        districts: [
            {
                name: 'Khulna',
                subAreas: [
                    'Khalishpur',
                    'Sonadanga',
                    'Kotwali',
                    'Daulatpur',
                    'Khan Jahan Ali',
                    'Dighalia',
                    'Dumuria',
                    'Batiaghata',
                    'Paikgachha',
                    'Phultala',
                    'Rupsa',
                    'Terokhada',
                    'Koyra',
                ],
            },
            {
                name: 'Jashore',
                subAreas: [
                    'Jashore Sadar',
                    'Abhaynagar',
                    'Bagherpara',
                    'Chaugachha',
                    'Jhikargachha',
                    'Keshabpur',
                    'Manirampur',
                    'Sharsha',
                ],
            },
            {
                name: 'Satkhira',
                subAreas: [
                    'Satkhira Sadar',
                    'Assasuni',
                    'Debhata',
                    'Kalaroa',
                    'Kaliganj',
                    'Shyamnagar',
                    'Tala',
                ],
            },
            {
                name: 'Bagerhat',
                subAreas: ['Bagerhat Sadar', 'Chitalmari', 'Fakirhat', 'Kachua', 'Mollahat', 'Mongla', 'Morrelganj', 'Rampal', 'Sarankhola'],
            },
            {
                name: 'Jhenaidah',
                subAreas: [
                    'Jhenaidah Sadar',
                    'Harinakunda',
                    'Kaliganj',
                    'Kotchandpur',
                    'Maheshpur',
                    'Shailkupa',
                ],
            },
            {
                name: 'Magura',
                subAreas: [
                    'Magura Sadar',
                    'Mohammadpur',
                    'Shalikha',
                    'Sreepur',
                ],
            },
            {
                name: 'Narail',
                subAreas: [
                    'Narail Sadar',
                    'Kalia',
                    'Lohagara',
                ],
            },
            {
                name: 'Kushtia',
                subAreas: [
                    'Kushtia Sadar',
                    'Bheramara',
                    'Daulatpur',
                    'Khoksa',
                    'Kumarkhali',
                    'Mirpur',
                ],
            },
            {
                name: 'Chuadanga',
                subAreas: [
                    'Chuadanga Sadar',
                    'Alamdanga',
                    'Damurhuda',
                    'Jibannagar',
                ],
            },
            {
                name: 'Meherpur',
                subAreas: [
                    'Meherpur Sadar',
                    'Gangni',
                    'Mujibnagar',
                ],
            },
        ],
    },

    {
        name: 'Barishal',
        districts: [
            {
                name: 'Barishal',
                subAreas: [
                    'Barishal Sadar',
                    'Agailjhara',
                    'Babuganj',
                    'Bakerganj',
                    'Banaripara',
                    'Gaurnadi',
                    'Hizla',
                    'Mehendiganj',
                    'Muladi',
                    'Wazirpur',
                ],
            },
            {
                name: 'Bhola',
                subAreas: [
                    'Bhola Sadar',
                    'Burhanuddin',
                    'Char Fasson',
                    'Daulatkhan',
                    'Lalmohan',
                    'Manpura',
                    'Tazumuddin',
                ],
            },
            {
                name: 'Patuakhali',
                subAreas: [
                    'Patuakhali Sadar',
                    'Bauphal',
                    'Dashmina',
                    'Dumki',
                    'Galachipa',
                    'Kalapara',
                    'Mirzaganj',
                    'Rangabali',
                ],
            },
            {
                name: 'Pirojpur',
                subAreas: [
                    'Pirojpur Sadar',
                    'Bhandaria',
                    'Kawkhali',
                    'Mathbaria',
                    'Nazirpur',
                    'Nesarabad',
                    'Zianagar',
                ],
            },
            {
                name: 'Jhalokati',
                subAreas: [
                    'Jhalokati Sadar',
                    'Kathalia',
                    'Nalchity',
                    'Rajapur',
                ],
            },
            {
                name: 'Barguna',
                subAreas: [
                    'Barguna Sadar',
                    'Amtali',
                    'Bamna',
                    'Betagi',
                    'Patharghata',
                    'Taltali',
                ],
            },
        ],
    },

    {
        name: 'Sylhet',
        districts: [
            {
                name: 'Sylhet',
                subAreas: [
                    'Zindabazar',
                    'Sylhet Sadar',
                    'Beanibazar',
                    'Bishwanath',
                    'Companiganj',
                    'Fenchuganj',
                    'Golapganj',
                    'Gowainghat',
                    'Jaintiapur',
                    'Kanaighat',
                    'Osmani Nagar',
                    'South Surma',
                    'Zakiganj',
                ],
            },
            {
                name: 'Moulvibazar',
                subAreas: [
                    'Moulvibazar Sadar',
                    'Barlekha',
                    'Juri',
                    'Kamalganj',
                    'Kulaura',
                    'Rajnagar',
                    'Sreemangal',
                ],
            },
            {
                name: 'Habiganj',
                subAreas: [
                    'Habiganj Sadar',
                    'Ajmiriganj',
                    'Bahubal',
                    'Baniachong',
                    'Chunarughat',
                    'Lakhai',
                    'Madhabpur',
                    'Nabiganj',
                    'Shayestaganj',
                ],
            },
            {
                name: 'Sunamganj',
                subAreas: [
                    'Sunamganj Sadar',
                    'Bishwambharpur',
                    'Chhatak',
                    'Derai',
                    'Dharampasha',
                    'Dowarabazar',
                    'Jagannathpur',
                    'Jamalganj',
                    'Shalla',
                    'South Sunamganj',
                    'Tahirpur',
                ],
            },
        ],
    },

    {
        name: 'Rangpur',
        districts: [
            {
                name: 'Rangpur',
                subAreas: [
                    'Rangpur Sadar',
                    'Badarganj',
                    'Gangachara',
                    'Kaunia',
                    'Mithapukur',
                    'Pirgachha',
                    'Pirganj',
                    'Taraganj',
                ],
            },
            {
                name: 'Dinajpur',
                subAreas: [
                    'Dinajpur Sadar',
                    'Birampur',
                    'Birganj',
                    'Biral',
                    'Bochaganj',
                    'Chirirbandar',
                    'Fulbari',
                    'Ghoraghat',
                    'Hakimpur',
                    'Kaharole',
                    'Khansama',
                    'Nawabganj',
                    'Parbatipur',
                ],
            },
            {
                name: 'Kurigram',
                subAreas: [
                    'Kurigram Sadar',
                    'Bhurungamari',
                    'Char Rajibpur','Chilmari','Phulbari', 'Nageshwari','Rajarhat','Raumari','Ulipur',
                ],
            },
            {
                name: 'Gaibandha',
                subAreas: [
                    'Gaibandha Sadar',
                    'Fulchhari',
                    'Gobindaganj',
                    'Palashbari',
                    'Sadullapur',
                    'Saghata',
                    'Sundarganj',
                ],
            },
            {
                name: 'Nilphamari',
                subAreas: [
                    'Nilphamari Sadar',
                    'Dimla',
                    'Domar',
                    'Jaldhaka',
                    'Kishoreganj',
                    'Saidpur',
                ],
            },
            {
                name: 'Lalmonirhat',
                subAreas: [
                    'Lalmonirhat Sadar',
                    'Aditmari',
                    'Hatibandha',
                    'Kaliganj',
                    'Patgram',
                ],
            },
            {
                name: 'Panchagarh',
                subAreas: [
                    'Panchagarh Sadar',
                    'Atwari',
                    'Boda',
                    'Debiganj',
                    'Tetulia',
                ],
            },
            {
                name: 'Thakurgaon',
                subAreas: [
                    'Thakurgaon Sadar',
                    'Baliadangi',
                    'Haripur',
                    'Pirganj',
                    'Ranisankail',
                ],
            },
        ],
    },

    {
        name: 'Mymensingh',
        districts: [
            {
                name: 'Mymensingh',
                subAreas: [
                    'Mymensingh Sadar',
                    'Bhaluka',
                    'Dhobaura',
                    'Fulbaria',
                    'Gaffargaon',
                    'Gauripur',
                    'Haluaghat',
                    'Ishwarganj',
                    'Muktagachha',
                    'Nandail',
                    'Phulpur',
                    'Trishal',
                ],
            },
            {
                name: 'Jamalpur',
                subAreas: [
                    'Jamalpur Sadar',
                    'Bakshiganj',
                    'Dewanganj',
                    'Islampur',
                    'Madarganj',
                    'Melandaha',
                    'Sarishabari',
                ],
            },
            {
                name: 'Netrokona',
                subAreas: [
                    'Netrokona Sadar',
                    'Atpara',
                    'Barhatta',
                    'Durgapur',
                    'Khaliajuri',
                    'Kalmakanda',
                    'Kendua',
                    'Madan',
                    'Mohanganj',
                    'Purbadhala',
                ],
            },
            {
                name: 'Sherpur',
                subAreas: [
                    'Sherpur Sadar',
                    'Jhenaigati',
                    'Nakla',
                    'Nalitabari',
                    'Sreebardi',
                ],
            },
        ],
    },
];


export const districts = ["Dhaka", "Faridpur", "Gazipur", "Gopalganj", "Kishoreganj", "Madaripur", "Manikganj", "Munshiganj", "Narayanganj", "Narsingdi", "Rajbari", "Shariatpur", "Tangail", "Bagerhat", "Chuadanga", "Jashore", "Jhenaidah", "Khulna", "Kushtia", "Magura", "Meherpur", "Narail", "Satkhira", "Bandarban", "Brahmanbaria", "Chandpur", "Chattogram", "Cumilla", "Cox's Bazar", "Feni", "Khagrachhari", "Lakshmipur", "Noakhali", "Rangamati", "Bogura", "Joypurhat", "Naogaon", "Natore", "Chapainawabganj", "Pabna", "Rajshahi", "Sirajganj", "Habiganj", "Moulvibazar", "Sunamganj", "Sylhet", "Dinajpur", "Gaibandha", "Kurigram", "Lalmonirhat", "Nilphamari", "Panchagarh", "Rangpur", "Thakurgaon", "Jamalpur", "Mymensingh", "Netrokona", "Sherpur", "Barguna", "Barishal", "Bhola", "Jhalokathi", "Patuakhali", "Pirojpur"]; 


export const divisions = ["Dhaka", "Chattogram", "Rajshahi", "Khulna", "Barishal", "Sylhet", "Rangpur", "Mymensingh"];